version: '3.3'

services:
  nginx-proxy-server:
    build: 
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - tms_rest_server
    ports:
      - 80:80
  postgres_db:
    image: postgres:14.4-alpine
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./storage-data:/var/lib/postgresql/data
    ports:
      - 5432:${POSTGRES_PORT}
  
  tms_rest_server:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres_db
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres_db
    volumes:
      - ./:/app
    ports:
      - 3000:${APP_PORT}
