version: '3.3'

services:
  tms_rest_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tms_rest_server
    stdin_open: true
    tty: true
    env_file: .env
    volumes:
      - ./:/app
    ports:
      - 3000:3000
